print("Program starting.")
Name = input("What is your name: ")
num1 = float(input("Enter a floating point number: "))
num2 = float(input("Enter a second floating point number: "))
print(f"{Name} you gave numbers {num1} and {num2}.")
product = round(num1 * num2, 2)
print(f"Multiplying first and second number will result in product {product}")
print("Program ending.")